import { IWavesBasicConfig, IWavesConfig } from '../interfaces';
import { TRANSACTION_TYPE, TRANSACTION_TYPE_NUMBER, TRANSACTION_TYPE_VERSION } from '@waves/signature-generator';
export declare const WAVES = "WAVES";
export declare const MAINNET_BYTE: number;
export declare const TESTNET_BYTE: number;
export declare const INITIAL_NONCE = 0;
export declare const ADDRESS_BYTE = 1;
export declare const ALIAS_BYTE = 2;
export declare const ISSUE_TX: TRANSACTION_TYPE_NUMBER;
export declare const TRANSFER_TX: TRANSACTION_TYPE_NUMBER;
export declare const REISSUE_TX: TRANSACTION_TYPE_NUMBER;
export declare const BURN_TX: TRANSACTION_TYPE_NUMBER;
export declare const EXCHANGE_TX: TRANSACTION_TYPE_NUMBER;
export declare const LEASE_TX: TRANSACTION_TYPE_NUMBER;
export declare const CANCEL_LEASING_TX: TRANSACTION_TYPE_NUMBER;
export declare const CREATE_ALIAS_TX: TRANSACTION_TYPE_NUMBER;
export declare const MASS_TRANSFER_TX: TRANSACTION_TYPE_NUMBER;
export declare const DATA_TX: TRANSACTION_TYPE_NUMBER;
export declare const SET_SCRIPT_TX: TRANSACTION_TYPE_NUMBER;
export declare const SPONSORSHIP_TX: TRANSACTION_TYPE_NUMBER;
export declare const ISSUE_TX_VERSION: TRANSACTION_TYPE_VERSION;
export declare const TRANSFER_TX_VERSION: TRANSACTION_TYPE_VERSION;
export declare const REISSUE_TX_VERSION: TRANSACTION_TYPE_VERSION;
export declare const BURN_TX_VERSION: TRANSACTION_TYPE_VERSION;
export declare const EXCHANGE_TX_VERSION: TRANSACTION_TYPE_VERSION;
export declare const LEASE_TX_VERSION: TRANSACTION_TYPE_VERSION;
export declare const CANCEL_LEASING_TX_VERSION: TRANSACTION_TYPE_VERSION;
export declare const CREATE_ALIAS_TX_VERSION: TRANSACTION_TYPE_VERSION;
export declare const MASS_TRANSFER_TX_VERSION: TRANSACTION_TYPE_VERSION;
export declare const DATA_TX_VERSION: TRANSACTION_TYPE_VERSION;
export declare const SET_SCRIPT_TX_VERSION: TRANSACTION_TYPE_VERSION;
export declare const SPONSORSHIP_TX_VERSION: TRANSACTION_TYPE_VERSION;
export declare const ISSUE_TX_NAME: TRANSACTION_TYPE;
export declare const TRANSFER_TX_NAME: TRANSACTION_TYPE;
export declare const REISSUE_TX_NAME: TRANSACTION_TYPE;
export declare const BURN_TX_NAME: TRANSACTION_TYPE;
export declare const EXCHANGE_TX_NAME: TRANSACTION_TYPE;
export declare const LEASE_TX_NAME: TRANSACTION_TYPE;
export declare const CANCEL_LEASING_TX_NAME: TRANSACTION_TYPE;
export declare const CREATE_ALIAS_TX_NAME: TRANSACTION_TYPE;
export declare const MASS_TRANSFER_TX_NAME: TRANSACTION_TYPE;
export declare const DATA_TX_NAME: TRANSACTION_TYPE;
export declare const SET_SCRIPT_TX_NAME: TRANSACTION_TYPE;
export declare const SPONSORSHIP_TX_NAME: TRANSACTION_TYPE;
export declare const PRIVATE_KEY_LENGTH = 32;
export declare const PUBLIC_KEY_LENGTH = 32;
export declare const MINIMUM_FEE = 100000;
export declare const MINIMUM_ISSUE_FEE = 100000000;
export declare const MINIMUM_MATCHER_FEE = 300000;
export declare const MINIMUM_DATA_FEE_PER_KB = 100000;
export declare const TRANSFER_ATTACHMENT_BYTE_LIMIT = 140;
export declare const DEFAULT_MIN_SEED_LENGTH = 25;
export declare const DEFAULT_ORDER_EXPIRATION_DAYS = 20;
export declare const DEFAULT_BASIC_CONFIG: IWavesBasicConfig;
export declare const DEFAULT_MAINNET_CONFIG: IWavesConfig;
export declare const DEFAULT_TESTNET_CONFIG: IWavesConfig;
export declare const WAVES_V1_ISSUE_TX: {
    assetId: string;
    decimals: number;
    description: string;
    fee: number;
    height: number;
    id: string;
    name: string;
    quantity: number;
    reissuable: boolean;
    sender: string;
    senderPublicKey: string;
    signature: string;
    timestamp: number;
    type: TRANSACTION_TYPE_NUMBER;
};
export declare const BROADCAST_PATH = "/transactions/broadcast";
